name: 1. Quality Assurance

on:
  push:
    branches:
      - 'main'
      - 'bundestag-2025'
      - 'github-workflows'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs: 
  quality:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check .

  tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      COLLECTION_NAME: ${{ vars.COLLECTION_NAME }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Install dependencies
        run: |
          uv sync --frozen --all-groups

      - name: Run tests 
        run: |
          uv run pytest tests