name: 1. Quality Assurance

on:
  push:
    branches:
      - 'main'
      - 'bundestag-2025'
      - 'github-workflows'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs: 
  quality:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check .

  tests:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      COLLECTION_NAME: ${{ vars.COLLECTION_NAME }}
  
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t electify .
      - name: Run Docker container   
        run: docker run -d --name electify_container -p 8080:8080 electify
      - name: Install playwright
        run: docker exec electify_container uv run playwright install chromium --with-deps
      - name: Run tests
        run: docker exec electify_container uv run pytest tests
      - name: Stop and remove Docker container
        run: docker stop electify_container && docker rm electify_container